# Generated by Django 3.0.5 on 2020-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('check_in_date', models.DateField(help_text='format : YYYY-MM-DD', max_length=10)),
                ('check_out_date', models.DateField(help_text='format : YYYY-MM-DD', max_length=10)),
                ('room', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Large', 'Large')], default='Single', max_length=6, null=True)),
            ],
        ),
    ]
